stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo 'testing'

build:
  image: docker
  stage: build
  script:
    - docker login -u $GITLAB_USER_LOGIN -p $GIT_TOKEN
    - docker build -t $CI_REGISTRY_IMAGE .
    - echo 'building complete'

deploy:
  stage: deploy
  script:
    - echo 'deploying'
