stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo 'testing'

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t CI_REGISTRY .
    - echo 'building'

deploy:
  stage: deploy
  script:
    - echo 'deploying'
