stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo 'testing'

build:
  image: docker
  stage: build
  script:
    - env
    - docker build -t $CI_REGISTRY_IMAGE .
    - echo 'building'

deploy:
  stage: deploy
  script:
    - echo 'deploying'
