stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo 'testing'

build:
  image: docker
  services:
    - dind
  stage: build
  variables:
    ARTIFACT: $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME
  script:
    - env
    - docker login --password $CI_JOB_TOKEN --user $GITLAB_USER_LOGIN
    - docker build -t $ARTIFACT:latest .
    - docker publish $ARTIFACT
    - echo 'building complete'

deploy:
  stage: deploy
  script:
    - echo 'deploying'
