stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo 'testing'

build:
  image: docker
  services:
    - docker:dind
  stage: build
  variables:
    ARTIFACT: $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME
    # DOCKER_HOST: tcp://docker:2375
    # DOCKER_TLS_CERTDIR: ""
  script:
    - env
    - docker login --password-stdin $GIT_TOKEN --username $GITLAB_USER_LOGIN
    - docker build -t $ARTIFACT:latest .
    - docker publish $ARTIFACT
    - echo 'building complete'

deploy:
  stage: deploy
  script:
    - echo 'deploying'
